name: Build Fyne App (Linux, Windows, macOS)

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.6"

      - name: Install fyne tool
        run: go install fyne.io/tools/cmd/fyne@v1.7.0

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libgl1-mesa-dev xorg-dev libxkbcommon-dev -y

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: v2.6.2
          args: --verbose --timeout=10m
          working-directory: ./app

      - name: Package Windows .exe
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $versionFlag = ""
          if ("${{ github.ref_type }}" -eq "tag") {
            $versionFlag = "-version ${{ github.ref_name }}"
          }

          fyne package -os windows --source-dir app -icon assets\Icon.png -release $versionFlag
          dir app

      - name: Package Linux binary
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          VERSION_FLAG=""
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION_FLAG="-version ${{ github.ref_name }}"
          fi

          fyne package -os linux --source-dir app -icon assets/Icon.png -release $VERSION_FLAG
          ls -la

      - name: Package macOS .app
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          VERSION_FLAG=""
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION_FLAG="-version ${{ github.ref_name }}"
          fi

          fyne package -os darwin --source-dir app -icon assets/Icon.png -release $VERSION_FLAG
          ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            **/*.exe
            **/*.tar.xz
            **/*.app

  release:
    if: github.ref_type == 'tag'
    needs: build

    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: build-${{ matrix.os }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/*.exe
            **/*.tar.xz
            **/*.app
